<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GroupuseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
    // 一件だけinsertする
    DB::table('groupuses')->insert([
      'group_name' => 'スパルタテニス',
      'representative_name' => '小野 登',
      'email' => 'dqj05611@icloud.com',
      'post_code' => '0200863',
      'adrress' => '盛岡市南仙北',
      'phone_number' => '09049340765',
      'workplace' => '盛岡市東仙北',
      'workplace_phone_number' => '0196554432',
      'date_of_use' => '2023-12-10',
      'time_of_use' => '14:00',
      'facilities_to_use' => '町営テニスコート',
      'equipment_to_use' => 'ネット',
      'activity_contents' => "平泉町を盛り上げるために、\n日頃の練習の成果を発揮して、\n優勝を町民に届ける。",
      'member1_name' => '判',
      'member1_adress' => '平泉町平泉',
      'member2_name' => '宮平',
      'member2_adress' => '平泉町平泉',
      'member3_name' => '山内',
      'member3_adress' => '平泉町平泉',
      'member4_name' => 'マキ',
      'member4_adress' => '平泉町長島',
      'member5_name' => '加藤',
      'member5_adress' => '平泉町平泉',
      'member6_name' => '吉田',
      'member6_adress' => '平泉町長島',
      'member7_name' => '三浦',
      'member7_adress' => '一関市中里',
      'member8_name' => '判',
      'member8_adress' => '平泉町平泉',
      'member9_name' => '判',
      'member9_adress' => '平泉町平泉',
      'member10_name' => '判',
      'member10_adress' => '平泉町平泉',
      'member11_name' => '判',
      'member11_adress' => '平泉町平泉',
      'member12_name' => '判',
      'member12_adress' => '平泉町平泉',
      'member13_name' => '判',
      'member13_adress' => '平泉町平泉',
      'member14_name' => '判',
      'member14_adress' => '平泉町平泉',
      'member15_name' => '判',
      'member15_adress' => '平泉町平泉',
      'member16_name' => '判',
      'member16_adress' => '平泉町平泉',
      'member17_name' => '判',
      'member17_adress' => '平泉町平泉',
      'member18_name' => '判',
      'member18_adress' => '平泉町平泉',
      'member19_name' => '判',
      'member19_adress' => '平泉町平泉',
      'member20_name' => '判',
      'member20_adress' => '平泉町平泉',
      'created_at' => date('Y-m-d H:i:s'),
      'updated_at' => date('Y-m-d H:i:s'),
    ]);

    # paramに配列を代入
    $param = [
      [
        'group_name' => 'バスケットボールキャンプ',
        'representative_name' => "小野登",
        'email' => 'dqj05611@gmail.com',
        'post_code' => '0200863',
        'adrress' => '盛岡市南仙北',
        'phone_number' => '09049340765',
        'workplace' => '盛岡市東仙北',
        'workplace_phone_number' => '0196664432',
        'date_of_use' => '2023-12-11',
        'time_of_use' => '13:00',
        'facilities_to_use' => '平泉中学校',
        'equipment_to_use' => 'バスケットリング',
        'activity_contents' => "平泉町を盛り上げるために、\n日頃の練習の成果を発揮して、\n菊池の卒業した花巻東と対戦して必ず勝利を町民に届ける。",
        'member1_name' => '判',
        'member1_adress' => '平泉町平泉',
        'member2_name' => '宮平',
        'member2_adress' => '平泉町平泉',
        'member3_name' => '山内',
        'member3_adress' => '平泉町平泉',
        'member4_name' => 'マキ',
        'member4_adress' => '平泉町長島',
        'member5_name' => '加藤',
        'member5_adress' => '平泉町平泉',
        'member6_name' => '吉田',
        'member6_adress' => '平泉町長島',
        'member7_name' => '三浦',
        'member7_adress' => '一関市中里',
        'member8_name' => '判',
        'member8_adress' => '平泉町平泉',
        'member9_name' => '判',
        'member9_adress' => '平泉町平泉',
        'member10_name' => '判',
        'member10_adress' => '平泉町平泉',
        'member11_name' => '判',
        'member11_adress' => '平泉町平泉',
        'member12_name' => '判',
        'member12_adress' => '平泉町平泉',
        'member13_name' => '判',
        'member13_adress' => '平泉町平泉',
        'member14_name' => '判',
        'member14_adress' => '平泉町平泉',
        'member15_name' => '判',
        'member15_adress' => '平泉町平泉',
        'member16_name' => '判',
        'member16_adress' => '平泉町平泉',
        'member17_name' => '判',
        'member17_adress' => '平泉町平泉',
        'member18_name' => '判',
        'member18_adress' => '平泉町平泉',
        'member19_name' => '判',
        'member19_adress' => '平泉町平泉',
        'member20_name' => '判',
        'member20_adress' => '平泉町平泉',
        'created_at' => date('Y-m-d H:i:s'),
        'updated_at' => date('Y-m-d H:i:s'),
      ],
      [
        'group_name' => 'スパルタフットサルキャンプ',
        'representative_name' => '小野　登',
        'email' => 'yoshiyuki.simazaki.fss@gmail.com',
        'post_code' => '0200863',
        'adrress' => '盛岡市南仙北',
        'phone_number' => '09048340765',
        'workplace' => '盛岡市南仙北',
        'workplace_phone_number' => '016664432',
        'date_of_use' => '2023-12-13',
        'time_of_use' => '13:00',
        'facilities_to_use' => '長島体育館',
        'equipment_to_use' => 'ベース',
        'activity_contents' => "一関を盛り上げるために、日頃の練習の成果を発揮して、佐々木郎喜の卒業した大船渡高と対戦して必ず勝利を町民に届ける。",
        'member1_name' => '大判',
        'member1_adress' => '平泉町平泉',
        'member2_name' => '宮平',
        'member2_adress' => '平泉町平泉',
        'member3_name' => '山内',
        'member3_adress' => '平泉町平泉',
        'member4_name' => 'マキ',
        'member4_adress' => '平泉町長島',
        'member5_name' => '加藤',
        'member5_adress' => '平泉町平泉',
        'member6_name' => '吉田',
        'member6_adress' => '平泉町長島',
        'member7_name' => '三浦',
        'member7_adress' => '一関市中里',
        'member8_name' => '判',
        'member8_adress' => '平泉町平泉',
        'member9_name' => '判',
        'member9_adress' => '平泉町平泉',
        'member10_name' => '判',
        'member10_adress' => '平泉町平泉',
        'member11_name' => '判',
        'member11_adress' => '平泉町平泉',
        'member12_name' => '判',
        'member12_adress' => '平泉町平泉',
        'member13_name' => '判',
        'member13_adress' => '平泉町平泉',
        'member14_name' => '判',
        'member14_adress' => '平泉町平泉',
        'member15_name' => '判',
        'member15_adress' => '平泉町平泉',
        'member16_name' => '判',
        'member16_adress' => '平泉町平泉',
        'member17_name' => '判',
        'member17_adress' => '平泉町平泉',
        'member18_name' => '判',
        'member18_adress' => '平泉町平泉',
        'member19_name' => '判',
        'member19_adress' => '平泉町平泉',
        'member20_name' => '判',
        'member20_adress' => '平泉町平泉',
        'created_at' => date('Y-m-d H:i:s'),
        'updated_at' => date('Y-m-d H:i:s'),
      ]
    ];
    # DB::table->insertでレコードの登録
    DB::table('groupuses')->insert($param);
    }
}
